import {
  User,
  Client,
  GSTCredentialVault,
  PurchaseInvoiceRecord,
  GSTR2BRecord,
  ReconciliationItem,
  Task,
  CommunicationTemplate,
  ScheduledMessage,
  CommunicationLog,
  DocumentItem,
  AuditLogItem,
  DeveloperRelease,
  SystemHealthMetric,
  SystemNotification,
  RoleType,
  PermissionSet,
} from '@/types';

export const DEFAULT_PERMISSIONS: Record<RoleType, PermissionSet> = {
  SUPER_ADMIN: {
    viewClients: true,
    addClients: true,
    editClients: true,
    deleteClients: true,
    viewGstData: true,
    downloadGstReports: true,
    uploadDocuments: true,
    viewDocuments: true,
    deleteDocuments: true,
    runReconciliation: true,
    sendWhatsApp: true,
    sendEmail: true,
    scheduleMessages: true,
    viewReports: true,
    exportReports: true,
    manageStaff: true,
    assignClients: true,
    manageIntegrations: true,
    manageSettings: true,
    developerAccess: true,
    auditLogAccess: true,
  },
  ADMIN: {
    viewClients: true,
    addClients: true,
    editClients: true,
    deleteClients: true,
    viewGstData: true,
    downloadGstReports: true,
    uploadDocuments: true,
    viewDocuments: true,
    deleteDocuments: true,
    runReconciliation: true,
    sendWhatsApp: true,
    sendEmail: true,
    scheduleMessages: true,
    viewReports: true,
    exportReports: true,
    manageStaff: true,
    assignClients: true,
    manageIntegrations: true,
    manageSettings: true,
    developerAccess: false,
    auditLogAccess: true,
  },
  CA_SENIOR: {
    viewClients: true,
    addClients: true,
    editClients: true,
    deleteClients: false,
    viewGstData: true,
    downloadGstReports: true,
    uploadDocuments: true,
    viewDocuments: true,
    deleteDocuments: true,
    runReconciliation: true,
    sendWhatsApp: true,
    sendEmail: true,
    scheduleMessages: true,
    viewReports: true,
    exportReports: true,
    manageStaff: false,
    assignClients: true,
    manageIntegrations: true,
    manageSettings: true,
    developerAccess: false,
    auditLogAccess: true,
  },
  MANAGER: {
    viewClients: true,
    addClients: true,
    editClients: true,
    deleteClients: false,
    viewGstData: true,
    downloadGstReports: true,
    uploadDocuments: true,
    viewDocuments: true,
    deleteDocuments: false,
    runReconciliation: true,
    sendWhatsApp: true,
    sendEmail: true,
    scheduleMessages: true,
    viewReports: true,
    exportReports: true,
    manageStaff: false,
    assignClients: true,
    manageIntegrations: false,
    manageSettings: false,
    developerAccess: false,
    auditLogAccess: false,
  },
  STAFF: {
    viewClients: true,
    addClients: false,
    editClients: true,
    deleteClients: false,
    viewGstData: true,
    downloadGstReports: true,
    uploadDocuments: true,
    viewDocuments: true,
    deleteDocuments: false,
    runReconciliation: true,
    sendWhatsApp: true,
    sendEmail: true,
    scheduleMessages: false,
    viewReports: true,
    exportReports: true,
    manageStaff: false,
    assignClients: false,
    manageIntegrations: false,
    manageSettings: false,
    developerAccess: false,
    auditLogAccess: false,
  },
  ACCOUNTANT: {
    viewClients: true,
    addClients: false,
    editClients: false,
    deleteClients: false,
    viewGstData: true,
    downloadGstReports: true,
    uploadDocuments: true,
    viewDocuments: true,
    deleteDocuments: false,
    runReconciliation: true,
    sendWhatsApp: false,
    sendEmail: false,
    scheduleMessages: false,
    viewReports: true,
    exportReports: false,
    manageStaff: false,
    assignClients: false,
    manageIntegrations: false,
    manageSettings: false,
    developerAccess: false,
    auditLogAccess: false,
  },
  DATA_ENTRY: {
    viewClients: true,
    addClients: false,
    editClients: false,
    deleteClients: false,
    viewGstData: false,
    downloadGstReports: false,
    uploadDocuments: true,
    viewDocuments: true,
    deleteDocuments: false,
    runReconciliation: false,
    sendWhatsApp: false,
    sendEmail: false,
    scheduleMessages: false,
    viewReports: false,
    exportReports: false,
    manageStaff: false,
    assignClients: false,
    manageIntegrations: false,
    manageSettings: false,
    developerAccess: false,
    auditLogAccess: false,
  },
  VIEWER: {
    viewClients: true,
    addClients: false,
    editClients: false,
    deleteClients: false,
    viewGstData: true,
    downloadGstReports: false,
    uploadDocuments: false,
    viewDocuments: true,
    deleteDocuments: false,
    runReconciliation: false,
    sendWhatsApp: false,
    sendEmail: false,
    scheduleMessages: false,
    viewReports: true,
    exportReports: false,
    manageStaff: false,
    assignClients: false,
    manageIntegrations: false,
    manageSettings: false,
    developerAccess: false,
    auditLogAccess: false,
  },
  CUSTOM: {
    viewClients: true,
    addClients: true,
    editClients: true,
    deleteClients: false,
    viewGstData: true,
    downloadGstReports: true,
    uploadDocuments: true,
    viewDocuments: true,
    deleteDocuments: false,
    runReconciliation: true,
    sendWhatsApp: true,
    sendEmail: true,
    scheduleMessages: true,
    viewReports: true,
    exportReports: true,
    manageStaff: false,
    assignClients: false,
    manageIntegrations: false,
    manageSettings: false,
    developerAccess: false,
    auditLogAccess: false,
  },
};

export const INITIAL_USERS: User[] = [
  {
    id: 'usr-1',
    name: 'Neel Gabani',
    email: 'admin@taxnexus.io',
    phone: '+91 98250 12345',
    role: 'SUPER_ADMIN',
    roleTitle: 'Managing Partner & Senior CA',
    department: 'Executive / Practice Head',
    designation: 'FCA, Senior Partner',
    status: 'ACTIVE',
    mfaEnabled: true,
    assignedClientsCount: 0,
    permissions: DEFAULT_PERMISSIONS.SUPER_ADMIN,
    lastLogin: '2026-08-09 10:15 AM',
    loginHistory: [
      { timestamp: '2026-08-09 10:15 AM', ip: '103.24.120.45', device: 'Chrome on Windows 11', location: 'Ahmedabad, India' },
    ],
  },
  {
    id: 'usr-2',
    name: 'Sneha Patel',
    email: 'sneha.patel@taxnexus.io',
    phone: '+91 98795 67890',
    role: 'MANAGER',
    roleTitle: 'Taxation & GST Audit Manager',
    department: 'GST Compliance',
    designation: 'Senior Manager',
    status: 'ACTIVE',
    mfaEnabled: true,
    assignedClientsCount: 0,
    permissions: DEFAULT_PERMISSIONS.MANAGER,
    lastLogin: '2026-08-09 09:45 AM',
  },
  {
    id: 'usr-3',
    name: 'Amit Verma',
    email: 'amit.verma@taxnexus.io',
    phone: '+91 97234 54321',
    role: 'STAFF',
    roleTitle: 'Senior GST Executive',
    department: 'GST Audit & Returns',
    designation: 'Senior Associate',
    status: 'ACTIVE',
    mfaEnabled: false,
    assignedClientsCount: 0,
    permissions: DEFAULT_PERMISSIONS.STAFF,
    lastLogin: '2026-08-09 08:50 AM',
  },
];

// Clean Production-Ready Initial Datasets (Ready for Real Client Onboarding & Excel Imports)
export const INITIAL_CLIENTS: Client[] = [];

export const INITIAL_GST_VAULTS: GSTCredentialVault[] = [];

export const INITIAL_RECON_DATA: ReconciliationItem[] = [];

export const INITIAL_TASKS: Task[] = [];

export const INITIAL_DOCUMENTS: DocumentItem[] = [];

export const INITIAL_SCHEDULED_MESSAGES: ScheduledMessage[] = [];

export const COMMUNICATION_TEMPLATES: CommunicationTemplate[] = [
  {
    id: 'tpl-1',
    name: 'GSTR-1 Due Date Alert',
    category: 'GST_REMINDER',
    channel: 'WHATSAPP',
    subject: 'Action Required: GSTR-1 Due on {{dueDate}}',
    body: 'Dear {{clientName}},\n\nThis is a compliance reminder from {{firmName}} that your GSTR-1 for the period {{period}} is due on {{dueDate}}.\n\nPlease upload your outward sales registers to avoid late filing penalties.\n\nRegards,\n{{firmName}} Compliance Team',
    variables: ['clientName', 'firmName', 'period', 'dueDate'],
    updatedAt: '2026-08-09',
  },
  {
    id: 'tpl-2',
    name: 'GSTR-3B Tax Liability & Payment Notice',
    category: 'TAX_PAYMENT_ALERT',
    channel: 'WHATSAPP',
    subject: 'GSTR-3B Filing & Challan Payment for {{period}}',
    body: 'Dear {{clientName}},\n\nYour GSTR-3B return summary for {{period}} has been prepared by {{firmName}}.\n\nNet Tax Payable: {{taxAmount}}\nDue Date: {{dueDate}}\n\nPlease review and approve for submission.\n\nRegards,\n{{firmName}}',
    variables: ['clientName', 'period', 'taxAmount', 'dueDate', 'firmName'],
    updatedAt: '2026-08-09',
  },
  {
    id: 'tpl-3',
    name: 'Missing Supplier Invoice in 2B Notice',
    category: 'PURCHASE_BILL_REQUEST',
    channel: 'EMAIL',
    subject: 'ITC At Risk: Invoices Missing in GSTR-2B for {{period}}',
    body: 'Dear {{clientName}},\n\nDuring our automated GSTR-2B reconciliation for {{period}}, we identified invoices from your suppliers that have not been reflected in the GST portal.\n\nPlease ask your vendors to file their GSTR-1 immediately to ensure you receive eligible Input Tax Credit.\n\nRegards,\n{{firmName}} Audit Division',
    variables: ['clientName', 'period', 'firmName'],
    updatedAt: '2026-08-09',
  },
];

export const INITIAL_AUDIT_LOGS: AuditLogItem[] = [
  {
    id: 'aud-init-1',
    userId: 'usr-1',
    userName: 'Neel Gabani',
    userRole: 'Super Admin',
    action: 'Practice Workspace Initialized',
    resourceType: 'SYSTEM',
    ipAddress: '127.0.0.1',
    userAgent: 'TaxNexus Practice Core Engine v2.4.0',
    timestamp: '09 Aug 2026, 09:00 AM',
    details: 'Clean production workspace ready for client onboarding and compliance filings.',
  },
];

export const DEVELOPER_RELEASES: DeveloperRelease[] = [
  {
    version: 'v2.4.0',
    releaseDate: '09 Aug 2026',
    status: 'DEPLOYED',
    features: [
      'Added Automated Dual Excel Match Engine (GSTR-2B vs Purchase Register)',
      'Added Bulk Client Excel Import & Export',
    ],
    improvements: [
      'Production Clean Slate Deployment Mode',
      'Enhanced Security & RBAC Scoping',
    ],
    bugFixes: [
      'Resolved invoice number fuzzy normalization edge cases',
    ],
  },
];

export const SYSTEM_HEALTH_METRICS: SystemHealthMetric[] = [
  { service: 'API Gateway', status: 'OPERATIONAL', latencyMs: 18, uptime: '99.98%', lastChecked: 'Just now' },
  { service: 'GSP Connect Service', status: 'OPERATIONAL', latencyMs: 24, uptime: '99.95%', lastChecked: 'Just now' },
  { service: 'Database Core', status: 'OPERATIONAL', latencyMs: 8, uptime: '100%', lastChecked: 'Just now' },
  { service: 'AI Match Engine', status: 'OPERATIONAL', latencyMs: 42, uptime: '99.99%', lastChecked: 'Just now' },
];

export const SYSTEM_NOTIFICATIONS: SystemNotification[] = [
  {
    id: 'notif-1',
    title: 'Workspace Initialized',
    message: 'TaxNexus Practice Management SaaS is ready for client onboarding.',
    type: 'INFO',
    category: 'SYSTEM',
    timestamp: 'Just now',
    read: false,
  },
];

export const INITIAL_COMMUNICATION_TEMPLATES = COMMUNICATION_TEMPLATES;
export const INITIAL_DEVELOPER_RELEASES = DEVELOPER_RELEASES;
export const INITIAL_SYSTEM_HEALTH = SYSTEM_HEALTH_METRICS;
export const INITIAL_NOTIFICATIONS = SYSTEM_NOTIFICATIONS;
